### ISSUE TITLE
Question: How to run remote watch on user defined port

### ISSUE THREAD

**Issue by yenly** [hashicorp/next-remote-watch#12]
I previous have a custom defined port to run my next app using
```js
"dev": "next -p 8888"
```

I tried adding port to below and it doesn't work.
```js
"dev:watch": "next-remote-watch ./notes -p 8888",
```

Is there a way to set next-remote-watch to do this?

**Comment by kylemac** [comment]
hey @yenly, we actually use the `-p` flag for our `polling` option, but we do respect an environment variable called `PORT` to override `3000` as your port of choice. 

there's a bunch of different ways you might want to set `process.env.PORT`, depending on your hosting setup, but the most basic command would be:

```js
"dev:watch": "PORT=8888 next-remote-watch ./notes",
```

here's the part of the code that checks for your PORT env variable: https://github.com/hashicorp/next-remote-watch/blob/master/bin/next-remote-watch#L36

and for good measure, here's the readme link on the `-p` polling option: https://github.com/hashicorp/next-remote-watch#optional-flags

hopefully this works for you. please close the issue if everything is working as you need it ❤️ 🙇‍♂️

**Comment by yenly** [comment]
@kylemac Thank you so much for the detailed response. It was helpful, and I can run the app on my own defined port.
