### ISSUE TITLE
Contributing: Adding unit tests to the project

### ISSUE THREAD

**Issue by floroz** [hashicorp/next-remote-watch#19]
Hello,

I have a use-case that is perfect for `next-remote-watch`.

One of our Next.js project has some content (`.mdx` files) that is loaded in the `getStaticProps` methods. However, changes to those files do not trigger a fast refresh/hot reload.

I have tried to use `next-remote-watch ./src/content/*` and it correctly triggers the refresh whenever content in the markdown is updated.

I am very keen in adopting the library but noticed that it uses undocumented APIs from Next (I suppose is the `app.server.hotReloader`?) and that there is no test coverage at the present.

Rather than creating and maintaining our own fork, I would like to know if you guys would be happy for us to contribute to the test coverage in the project.

**Comment by jescalan** [comment]
Yes, would be very happy to see that. Thank you!

**Comment by floroz** [comment]
> Yes, would be very happy to see that. Thank you!

Great, I will send you a PR by next week 👍
