### ISSUE TITLE
Dependency trimming

### ISSUE THREAD

**Issue by kanishka-work** [hashicorp/next-remote-watch#22]
Thanks for implementing this utility. I'm curious if you have any plans on refactoring the implementation to reduce the number of transitive dependencies?

**Comment by kanishka-work** [comment]
I was wondering if you are considering shopping for alternative direct dependencies such that the total transitive dependencies are reduced in the future, or if the implementation is fairly settled at this point?

**Comment by jescalan** [comment]
I still do not know what you're talking about honestly. We are not actively aiming to refactor this library right now, or considering any major changes or features. If anyone has suggestions, we are open to them!

**Comment by kanishka-work** [comment]
Okay, no worries. I will close this issue.

I was hesitating to add 75 transitive dependencies to my next site to use this utility, so I just wanted to figure out if that will always be the case or not. It may just be that the current direct dependencies are the best options in npm currently.

**Comment by jescalan** [comment]
Sounds good! Again you are more than welcome to look through the code and suggest changes if you'd like, in fact, that would be wonderful. This is in general a very slim package, and is only used in local development. That on top of the fact that nextjs itself surely has many, many hundreds of dependencies in its tree, many of them likely shared and deduped with this package, makes this not really stick out to me as a major issue.

**Comment by kanishka-work** [comment]
That's a good point about nextjs sharing dependencies. The main difference seems to be express. I can shop around for a lighter dependency alternative to express and report back.

**Comment by kanishka-work** [comment]
I ended up not needing a watcher for my use case, so I am not planning on finding a express alternative anymore.
