### ISSUE TITLE
Support `--port` argument

### ISSUE THREAD

**Issue by evantahler** [hashicorp/next-remote-watch#23]
It would be great if `next-remote-watch` also took `--port`, like `next dev` does... so we can change the port!

**Comment by evantahler** [comment]
But... `PORT=1234 next-remote-watch` works, so, this is fine!

**Comment by axsddlr** [comment]
`PORT=1234 next-remote-watch` does not work on npm start command unfortunately

**Comment by jescalan** [comment]
It should work fine. npm commands are just regular commands

**Comment by Axiverse** [comment]
@axsddlr if you're using windows try `set PORT=8000 & next-remote-watch`
