### ISSUE TITLE
server is undefined

### ISSUE THREAD

**Issue by jmayergit** [hashicorp/next-remote-watch#26]
```bash
node_modules/next-remote-watch/bin/next-remote-watch:47
          app.server.hotReloader.send('building')
                     ^

TypeError: Cannot read property 'hotReloader' of undefined
```

`"next": "^10.0.3",`

**Comment by kendallstrautman** [comment]
Hi @jmayergit, this is an issue with the [version of next](https://github.com/hashicorp/next-remote-watch/pull/15) you are using. Please use `v10.0.9` or greater. Let us know if that doesn't fix the issue!
