### ISSUE TITLE
next official support

### ISSUE THREAD

**Issue by ShaMan123** [hashicorp/next-remote-watch#41]
https://nextjs.org/docs/advanced-features/custom-server

**Comment by BRKalow** [comment]
Can you provide more context here? This is not an actionable issue.

**Comment by ShaMan123** [comment]
There are lots of examples in the link I added
It is quite straight forward...
Then you can use something like nodemon to run a dev server and you are all set

**Comment by BRKalow** [comment]
How does this relate to the functionality of this library? Those are docs for running a custom node server around a next app. This library specifically handles running a custom dev server which watches for changed files and reloads the browser.

Do you have a specific suggestion on something for `next-remote-watch`?

**Comment by ShaMan123** [comment]
I saw https://github.com/hashicorp/next-remote-watch#important-warnings-and-caveats
> This package utilizes undocumented APIs from next.js...

Using `nodemon` with a custom server and the following config should be stable as it doesn't use internals.

```json
nodemon.config.json
{
    "ignore": [
        ".next"
    ],
    "watch": [
        ".",
       "/path/to/what/ever"
    ],
    "ext": "js mjs cjs json ts jsx tsx"
}
```

```bash
nodemon --config nodemon.config.json customServer.js
```

Another approach I saw on SO suggested using `fs.utimes` to trigger next to reload

I wanted to use this repo in a repo I maintain but because it of the README I had to backoff.
