### ISSUE TITLE
Question: fast refresh for MDX files

### ISSUE THREAD

**Issue by edmundojr** [hashicorp/next-remote-watch#9]
Next.js 10 now supports [fast refresh for MDX files](https://nextjs.org/blog/next-10#fast-refresh-for-mdx), any chance this library can also support it?

I upgrade to Next.js 10 and still works fine still, but it does a full reload instead of fast refreshing.

**Comment by jescalan** [comment]
This library has nothing to do with mdx files and is specifically intended to do a full reload

**Comment by jescalan** [comment]
If you are looking to load mdx files as files through webpack, you can use the next mdx loader, or if you need more functionality, you can use [next-mdx-enhanced](https://github.com/hashicorp/next-mdx-enhanced), though there are many drawbacks to loading mdx files through webpack, primarily scale-related. It is not possible as far as i know for fast refresh to work for data loaded through `getStaticProps`, ever.

**Comment by edmundojr** [comment]
Thanks for the clarification @jescalan. I'm using [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote/), will dig to see if I can get it to fast refresh with `getStaticProps`, although as you say I don't think it's possible.

**Comment by gaearon** [comment]
https://github.com/hashicorp/next-remote-watch/issues/42
